### ISSUE TITLE
widget_loader must go after footer_scripts.html

### ISSUE THREAD

**Issue by electroniceagle** [osiloke/mezzanine_widgets#1]
Great little app!  The add widget buttons appeared but didn't function when {% widget_loader %} was placed in <head>.  Looking at your example,  I noticed that you placed it at the bottom of <body>.  My fault for not looking carefully at the example, but good to add a sentence to the installation notes.

**Comment by osiloke** [comment]
First issue, yay! Well ideally it should come after all other js scripts.
Thanks for the heads up, i'll make a note in the readme

**Comment by electroniceagle** [comment]
So far I have "hello world" working.  I'm trying to do a Bootstrap carousel widget.  Will put on github when I get it working.  

Brian Schott
bfschott@gmail.com

**Comment by osiloke** [comment]
Cool, let me know if you have any other issues. Maybe i'll make a Mezzanine Widget Site where smart peeps like you can post their creations (of course when it gets to v1.0)
