### ISSUE TITLE
login missing and add widgets with Mezzanine.1.0.10

### ISSUE THREAD

**Issue by electroniceagle** [osiloke/mezzanine_widgets#2]
This could be me, but I'm unable to get the example to work with a fresh virtualenv.  The widget function appears, the configure button appears, but the add widget button is not visible.  The login user panel is also missing.

```
^C(test)bschott@ironman:example$ pip freeze
Django==1.4
Mezzanine==1.0.10
Mezzanine-Widgets==0.1.0dev
Pillow==1.7.7
PyRSS2Gen==1.0.0
Pymacs==0.24-beta2
altgraph==0.7.1
amqplib==0.6.1
anyjson==0.3.1
bdist-mpkg==0.4.4
bleach==1.1.1
bonjour-py==0.3
django-classy-tags==0.3.4.1
docutils==0.8
filebrowser-safe==0.2.6
grappelli-safe==0.2.6
html5lib==0.95
include-server==3.1-toolwhip.1
macholib==1.3
modulegraph==0.8.1
pep8==0.6.1
py2app==0.5.3
pyOpenSSL==0.12
pyScss==1.0.8
pyflakes==0.5.0
pyobjc-core==2.3.2a0
pyobjc-framework-AddressBook==2.3.2a0
pyobjc-framework-AppleScriptKit==2.3.2a0
pyobjc-framework-AppleScriptObjC==2.3.2a0
pyobjc-framework-Automator==2.3.2a0
pyobjc-framework-CFNetwork==2.3.2a0
pyobjc-framework-CalendarStore==2.3.2a0
pyobjc-framework-Cocoa==2.3.2a0
pyobjc-framework-Collaboration==2.3.2a0
pyobjc-framework-CoreData==2.3.2a0
pyobjc-framework-CoreLocation==2.3.2a0
pyobjc-framework-CoreText==2.3.2a0
pyobjc-framework-DictionaryServices==2.3.2a0
pyobjc-framework-ExceptionHandling==2.3.2a0
pyobjc-framework-FSEvents==2.3.2a0
pyobjc-framework-InputMethodKit==2.3.2a0
pyobjc-framework-InstallerPlugins==2.3.2a0
pyobjc-framework-InstantMessage==2.3.2a0
pyobjc-framework-InterfaceBuilderKit==2.3.2a0
pyobjc-framework-LatentSemanticMapping==2.3.2a0
pyobjc-framework-LaunchServices==2.3.2a0
pyobjc-framework-Message==2.3.2a0
pyobjc-framework-OpenDirectory==2.3.2a0
pyobjc-framework-PreferencePanes==2.3.2a0
pyobjc-framework-PubSub==2.3.2a0
pyobjc-framework-QTKit==2.3.2a0
pyobjc-framework-Quartz==2.3.2a0
pyobjc-framework-ScreenSaver==2.3.2a0
pyobjc-framework-ScriptingBridge==2.3.2a0
pyobjc-framework-SearchKit==2.3.2a0
pyobjc-framework-ServerNotification==2.3.2a0
pyobjc-framework-ServiceManagement==2.3.2a0
pyobjc-framework-SyncServices==2.3.2a0
pyobjc-framework-SystemConfiguration==2.3.2a0
pyobjc-framework-WebKit==2.3.2a0
pyobjc-framework-XgridFoundation==2.3.2a0
pyparsing==1.5.6
python-dateutil==1.5
recaptcha-client==1.0.6
rope==0.9.3
ropemacs==0.6
ropemode==0.1-rc2
virtualenv==1.6.4
virtualenvwrapper==2.7.1
wsgiref==0.1.2
xattr==0.6.1
zc.buildout==1.5.2
zc.recipe.egg==1.3.2
zope.interface==3.5.1
```

**Comment by osiloke** [comment]
That's my bad, i took out the login user panel from the sample. I usually just login by going to /admin. I will put it back. Regarding the Add url not being on the page (i'm assuming that you are on the homepage). For now, you can only add widgets on regular mezzanine pages this is because widgets are attached to pages on the model level (Foreign Key). I put a little note last night, sorry if you missed that

**Comment by osiloke** [comment]
i should probably do a better example app, i just freed some time so i'm going to workon this app this weekend

**Comment by electroniceagle** [comment]
That's cool.  I was having one of those coding days where everything I did made things worse.  In my own template, the add button appears but the link is just a # to the same page.  Will debug some more.  I think 1.0.10 mezz is new, but I decided to look at it fresh this weekend.

**Comment by osiloke** [comment]
Yeah, so it's more or less that the widget.js file is not loaded, which means the template you are trying to use does not have {% widget_loader %} tag in place. I usually put it in the base template so you might want to do the following:

#python manage.py collecttemplates

This will put all templates from mezzanine into a folder, templates. The base.html template should be in there. Just place {% widget_loader %} after your jquery.js declaration. You can also just put it in the footer_scripts.html template and delete all other templates.

**Comment by electroniceagle** [comment]
It was a bug in my base.html.  Thanks for your help debugging.
